openapi: 3.0
info:
  title: FastAPI
  version: 0.1.0
paths:
  /tasks:
    get:
      summary: List Tasks
      operationId: list_tasks_tasks_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                title: Response List Tasks Tasks Get
                type: array
                items:
                  $ref: '#/components/schemas/Task'
    post:
      summary: Create Task
      operationId: create_task_tasks_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskCreate'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskCreateResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /tasks/{task_id}:
    put:
      summary: Update Task
      operationId: update_task_tasks__task_id__put
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
    delete:
      summary: Delete Task
      operationId: delete_task_tasks__task_id__delete
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /tasks/{task_id}/done:
    put:
      summary: Mark Task As Done
      operationId: mark_task_as_done_tasks__task_id__done_put
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
    delete:
      summary: Unmark Task As Done
      operationId: unmark_task_as_done_tasks__task_id__done_delete
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
components:
  schemas:
    HTTPValidationError:
      title: HTTPValidationError
      type: object
      properties:
        detail:
          title: Detail
          type: array
          items:
            $ref: '#/components/schemas/ValidationError'
    Task:
      title: Task
      required:
      - id
      type: object
      properties:
        title:
          title: Title
          type: string
          example: クリーニングを取りに行く
        id:
          title: Id
          type: integer
        done:
          title: Done
          type: boolean
          description: 完了フラグ
          default: false
    TaskCreate:
      title: TaskCreate
      type: object
      properties:
        title:
          title: Title
          type: string
          example: クリーニングを取りに行く
    TaskCreateResponse:
      title: TaskCreateResponse
      required:
      - id
      type: object
      properties:
        title:
          title: Title
          type: string
          example: クリーニングを取りに行く
        id:
          title: Id
          type: integer
    ValidationError:
      title: ValidationError
      required:
      - loc
      - msg
      - type
      type: object
      properties:
        loc:
          title: Location
          type: array
          items:
            anyOf:
            - type: string
            - type: integer
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
